dist: trusty
language: node_js
node_js:
  - 8
  - 9
install: true
before_install:
  - npm install -g lerna
before_script:
  - lerna bootstrap
env:
  - NODE_ENV=test
  - CI=true
install: yarn --frozen-lockfile
script:
  - npm test
cache: false