dist: trusty
language: node_js
node_js:
  - 8
env:
  - NODE_ENV=test
before_install:
  - npm i -g lerna
install: 
  - npm install
  - npm run bootstrap
  - npm run build
matrix:
  fast_finish: true
cache: false