dist: trusty
language: node_js
node_js:
  - 8
  - 9
env:
  - NODE_ENV=test
  - CI=true
install: 
  - "npm i -g lerna"
  - "npm i"
  - "lerna bootstrap"
script:
  - npm test
matrix:
  fast_finish: true
cache: false